number1 = int(input("Number 1: "))
number2 = int(input("Number 2: "))
print("Are the numbers equal: ", number1==number2)
print("First number bigger: ", number1>number2)
print("First number smaller: ", number1<number2)
